version: '3.8'

services:
  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    ports:
      - "3000:3000"
    environment:
      # Runtime environment variables (secrets)
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DUE_DATE=${DUE_DATE:-2025-02-25}
      - WINDOW_START=${WINDOW_START:-2025-02-15}
      - WINDOW_END=${WINDOW_END:-2025-03-10}
      - VENMO_RECIPIENT=${VENMO_RECIPIENT}
      - VENMO_AMOUNT=${VENMO_AMOUNT:-5}
      - VENMO_NOTE_TEMPLATE=${VENMO_NOTE_TEMPLATE:-Baby Bet — {name} — {date} — {code} — Due {dueDate}}
      - ADMIN_PASSCODE=${ADMIN_PASSCODE}
      - SESSION_TTL_HOURS=${SESSION_TTL_HOURS:-8}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add PostgreSQL for local development (alternative to Supabase)
# Uncomment this section if you want a local database instead of using Supabase
#
#   postgres:
#     image: postgres:15-alpine
#     environment:
#       POSTGRES_USER: babybet
#       POSTGRES_PASSWORD: babybet_dev
#       POSTGRES_DB: babybet
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./supabase/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U babybet"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#
# volumes:
#   postgres_data:

